/* Meh Golf - caddie chatter.
 *
 * Lines are grouped by situation. Each group is shuffled once per round (seeded,
 * so a given seed always produces the same order) and then drawn WITHOUT
 * replacement, so a line never repeats within a round. If a situation runs dry
 * -- e.g. a player who spends the whole round in the rough -- the draw falls
 * back to the situation-neutral "general" pool before it ever repeats itself.
 */
(function (global) {
  "use strict";

  const LINES = {

    /* ---- first shot of a hole ---- */
    tee: [
      "New hole, clean scorecard. The notebook forgets everything.",
      "Somewhere out there is a par. Go introduce yourself.",
      "The tee box: the only place on this course where nothing has gone wrong yet.",
      "Aim small, miss small. Or aim big and tell everyone you meant it.",
      "Every great round starts with one unremarkable shot.",
      "Fresh hole. No history, no grudges, no witnesses.",
      "The pencil is sharp and the hole is still theoretical. Enjoy this moment.",
      "Optimism is cheapest at the tee. Stock up.",
      "Nobody has ever three-putted from here.",
      "A blank line on the card is a beautiful thing. Try not to ruin it.",
      "Take a breath. The dots aren't going anywhere.",
      "Statistically, this is the best you will feel about this hole.",
      "One free re-roll is in your pocket. Don't spend it out of panic.",
      "The tee shot sets the tone. No pressure, obviously.",
      "Look at all that unspoiled paper.",
      "Somewhere between here and the cup, a decision will go badly. Delay it.",
      "Start conservative. Finish smug.",
      "This hole doesn't know you yet. First impressions matter.",
      "The cup is over there being smug. Do something about it.",
      "Long is fine. Wrong is expensive.",
      "No wind, no lie angle, no excuses. Just a die.",
      "The course was generated fairly. Whether it was generated kindly is another matter.",
      "Every hole is a par 6 until proven otherwise.",
      "Roll well and you'll look brilliant. Roll badly and you'll look philosophical.",
      "First shot. Nothing to protect, everything to gain.",
      "Somewhere a scorecard is holding its breath.",
      "The tee is the last honest place on a golf hole.",
      "Big number or small number, it all fits in the same box.",
      "Line it up. The rest is arithmetic and luck.",
      "You have played worse holes. You just don't remember them.",
      "A new hole is a rumour you haven't disproved yet.",
      "The card is blank here. Blank is the best it ever looks.",
      "Somewhere ahead there is trouble. It hasn't found you yet.",
      "Tee shots are cheap. Recovery shots are not.",
      "You get one free re-roll here. Only one, and only here.",
      "Begin sensibly. Sensible compounds.",
      "The hole is longest right now. It shrinks from here.",
      "Nothing has gone wrong. Savour the novelty.",
      "First swing of the hole. Set a tone you can live with.",
      "This is the shot with the most options and the least information."
    ],

    /* ---- lying on the fairway ---- */
    fairway: [
      "You're on the short grass. The die owes you a big one.",
      "Fairway means the ball runs an extra dot, and sails clean over the pines.",
      "This is the good stuff. Don't overthink it.",
      "From here you can fly the trees. Use that while you have it.",
      "A fairway lie is a gift. Gifts can be wasted.",
      "Short grass, long options. This is the fun part.",
      "The extra dot is free. The direction is on you.",
      "Trees mean nothing from here. Aim through them like they owe you money.",
      "Best lie on the course. Try to look like you planned it.",
      "Enjoy this. Statistically it won't last.",
      "The fairway is where good rounds are quietly assembled.",
      "You have the fairway bonus and a clear head. Spend them wisely.",
      "This is the shot the scorecard remembers fondly.",
      "One extra dot doesn't sound like much until you're one dot short.",
      "Clean lie, clean line. Go.",
      "The pines can't touch you here. Neither can excuses.",
      "From the fairway, ambition is affordable.",
      "You've earned a good number. The die may disagree.",
      "This is where the hole opens up. Walk through the door.",
      "Solid ground, solid odds. Rare combination.",
      "Take the aggressive line. You'll never have a better excuse.",
      "The fairway forgives distance. It does not forgive direction.",
      "A tidy lie for a tidy shot. Nothing fancy required.",
      "You're playing from the part of the map the designer liked.",
      "Fly the trees, land soft, look modest about it.",
      "This is the lie you were hoping for two shots ago.",
      "Good position. Now don't get clever about it.",
      "The extra dot is your friend. Introduce it to the cup.",
      "Everything is available from here. Choose one.",
      "There's no bad decision from the fairway. There are just expensive ones.",
      "A fairway lie makes a mediocre roll look competent.",
      "Nothing between you and the pin but arithmetic.",
      "This is the moment the hole becomes negotiable.",
      "The grass is short and the possibilities are long.",
      "Perfect lie. Now ruin it with a good decision.",
      "You're in the fairway. Somewhere, a scorecard exhales.",
      "Short grass. The map is finally on your side.",
      "You've bought yourself a free dot. Don't waste it going sideways.",
      "The pines are decorative from here.",
      "This lie makes big numbers safe. Use them.",
      "Fairway golf is boring golf, and boring golf wins.",
      "You're where you're supposed to be. Rare and fleeting.",
      "The bonus dot turns a 5 into a 6. That matters more than it sounds.",
      "Best surface on the map. Act accordingly.",
      "A clean lie and a clear head. Spend both now.",
      "From here the trees are someone else's problem.",
      "The fairway is a temporary condition. Capitalise.",
      "Nothing is in your way. Nothing is your excuse either."
    ],

    /* ---- lying on plain ground ---- */
    rough: [
      "The rough is honest, at least. No bonus, no penalty, no sympathy.",
      "Nothing helping you here, but nothing hurting you either.",
      "Plain ground. The die decides everything from here.",
      "A modest lie for a modest shot. There's no shame in modest.",
      "Neutral ground, neutral odds, neutral feelings.",
      "The rough doesn't punish you. It just declines to help.",
      "No bonus dot today. Play the number you get.",
      "Trees still block you from here. Plan accordingly.",
      "It's not trouble. It's just not opportunity.",
      "The most common lie in golf, and the least discussed.",
      "You're fine. Unremarkable, but fine.",
      "This is the part of the hole nobody writes home about.",
      "Straightforward lie, straightforward decision. Rare luxury.",
      "The rough asks nothing of you except a good direction.",
      "No help from the ground. All the help must come from the die.",
      "It's flat, it's plain, it's playable. Take the win.",
      "Somewhere between disaster and glory. Mostly the middle.",
      "The scorecard doesn't care where you played from.",
      "Standard lie, standard shot, standard hopes.",
      "You're not in trouble. Let's keep it that way.",
      "The rough is the course's way of saying nothing at all.",
      "No excuses available from here. Sorry.",
      "A perfectly ordinary spot for a perfectly ordinary shot.",
      "This is where most of golf actually happens.",
      "Nothing to fly over, nothing to fear. Just pick a line.",
      "The ground is neutral. Your ambition doesn't have to be.",
      "You could be worse off. You have been worse off.",
      "It's a blank canvas out here. Mostly beige.",
      "The rough has no opinion about your golf. Refreshing.",
      "Plain lie, clear head. That's most of the game.",
      "This is a shot you'll forget by the next hole.",
      "Nothing dramatic here. Dramatic is usually expensive.",
      "The die is doing all the work today.",
      "Fair ground. Whether the roll is fair is a separate question.",
      "No penalty, no gift. Just golf.",
      "You're playing from the default setting.",
      "This lie won't save you and it won't sink you.",
      "The rough: golf's largest and least interesting room.",
      "Aim well. That's the entire strategy from here.",
      "Nothing between you and a decent number but the die.",
      "It's not the fairway, but it's not the sand either.",
      "Middle of the map, middle of the road.",
      "The ball sits up fine. The rest is up to you.",
      "No terrain bonus. Consider it a fair fight.",
      "The rough is where rounds are quietly saved.",
      "Uncomplicated. Take advantage of that.",
      "This is a shot for competence, not heroism.",
      "You're neither blessed nor cursed. Play accordingly.",
      "The grass has no memory. Neither should you.",
      "Nothing exciting. Exciting is how bogeys start.",
      "Ordinary ground. Ordinary is undefeated.",
      "No terrain to blame. Just you and a number.",
      "The rough is where rounds are decided by boredom.",
      "You're playing from nowhere in particular.",
      "It's fine. Everything here is fine.",
      "The map has no opinion. Form your own.",
      "This is the lie that teaches patience.",
      "Nothing gained, nothing lost, nothing to say.",
      "Level ground and level expectations.",
      "A shot like any other. Most shots are.",
      "The rough asks only that you aim properly.",
      "Neutral terrain. Your decisions carry all the weight.",
      "No bonus. No penalty. No drama. Good.",
      "The kind of lie you'll never mention afterwards.",
      "Plain ground and a plain plan is usually enough.",
      "This isn't a problem. Don't turn it into one.",
      "The rough is the course being quiet.",
      "Nothing here will save a bad line.",
      "You're on ordinary grass in an ordinary spot. Play ordinary golf.",
      "The die is the only variable now.",
      "Somewhere between the tee and the cup, exactly as expected.",
      "There's no cleverness available here. Just accuracy.",
      "The unremarkable middle of an unremarkable shot.",
      "No help, no harm. That's the deal out here.",
      "Steady ground. Steady on."
    ],

    /* ---- lying in a bunker ---- */
    sand: [
      "Sand costs you a dot. Consider it a tax on ambition.",
      "The bunker: nature's way of asking if you were paying attention.",
      "Play the escape, not the hero shot. Out is better than close.",
      "Every golfer leaves a little something in the sand. Usually their scorecard.",
      "Minus one dot. The beach charges admission.",
      "An iron only carries 2 from here. Plan for less, not more.",
      "Get out first. Get clever later.",
      "The sand doesn't want you to leave. Insist.",
      "Short and safe beats long and buried.",
      "You'll travel one dot less. Adjust your ambitions by exactly that much.",
      "Bunkers are just fairways that went wrong.",
      "This is a shot about damage control, not glory.",
      "The sand takes a dot and offers nothing in return. Rude.",
      "Aim for grass. Any grass.",
      "One dot shorter than you'd like. Story of the game.",
      "The trap is doing its job. Don't help it.",
      "Escape is a perfectly respectable goal.",
      "Nobody has ever regretted getting out of a bunker.",
      "Sand is temporary. Bogeys are forever.",
      "The beach is lovely. Leave anyway.",
      "Minus one, and no flying over trees. Sand is thorough.",
      "Take your medicine. It's cheaper than the alternative.",
      "You're one dot poorer. Spend what's left carefully.",
      "The hero shot from a bunker is a myth with good PR.",
      "This is where a mulligan starts looking reasonable.",
      "Sand: the course's small print.",
      "Out sideways is still out.",
      "The die gives, the sand takes. Net result: less.",
      "Plan for the short version of your shot.",
      "You went in on purpose, obviously. Now come out on purpose.",
      "The bunker charges a dot and gives no receipt.",
      "Sand: where good rounds go to think about their choices.",
      "One dot lighter. Plan the shorter version.",
      "Escape now, apologise later.",
      "No flying the trees from sand. Remember that before you aim.",
      "The trap wants a second stroke. Deny it.",
      "Play for grass, not glory.",
      "Getting out cleanly is the entire objective.",
      "The sand shortens everything except the hole.",
      "You're paying a dot for the scenery."
    ],

    /* ---- within two dots of the cup ---- */
    close: [
      "You're a whisker away. Remember: one dot past still drops.",
      "Short game time. This is where notebooks are won.",
      "Close enough to smell it. Don't get greedy with the line.",
      "A putt moves exactly 1. Sometimes that's the whole trick.",
      "Two dots or fewer. This is the arithmetic that matters.",
      "Land on it, or roll one past. Both count.",
      "The cup is right there being patient.",
      "Don't blast it. This is a precision problem now.",
      "You can two-putt this. You can also three-putt it. Choose.",
      "The hard part is done. Please don't undo it.",
      "One good number and this is over.",
      "The overshoot rule is your friend. One past still drops.",
      "This is where the round gets decided, quietly.",
      "Close range. Small mistakes cost the same as big ones now.",
      "You've come a long way for this. Take a second.",
      "A putt is always 1. Predictability is a gift.",
      "The cup doesn't move. Everything else is negotiable.",
      "Nearly there. Nearly doesn't count.",
      "Count the dots twice. It's cheaper than a bogey.",
      "The difference between exact and nearly is one stroke.",
      "This is the shot you'll remember. Make it boring.",
      "Big rolls are a liability now. Small is beautiful.",
      "You need the right number, not the big number.",
      "Precision beats power inside two dots.",
      "The hole is close enough to be dangerous.",
      "Don't fly past it hoping. Fly past it exactly.",
      "One dot past still drops. Say it out loud before you commit.",
      "This is the moment the pencil hovers.",
      "Careful now. The card is watching.",
      "You're close. Close is where rounds go to die.",
      "The cup rewards exactness and nothing else.",
      "It's a short walk. Make it a short number.",
      "A putt is the most honest shot in the game.",
      "Nothing fancy. Fancy is how you end up three dots away again.",
      "The finish line is in view. Don't sprint past it. Well, not by two.",
      "Two dots out. This is a solvable problem.",
      "Inside two dots. Arithmetic time.",
      "The cup is a short number away. Find it.",
      "Exact or one past. Those are the winning answers.",
      "Small distances, big consequences.",
      "This is the shot that decides the box on the card.",
      "Precision now. Ambition earlier.",
      "You're near enough that guessing is expensive.",
      "The cup is close and entirely unforgiving.",
      "Count it out. Then count it out again.",
      "The short game is just careful counting.",
      "One dot decides this. Choose the right one.",
      "You're close enough that a mistake stings.",
      "Land it or roll past it. Nothing else scores.",
      "This is where the round quietly resolves.",
      "Nearly home. Nearly is doing a lot of work in that sentence."
    ],

    /* ---- water within a square of the ball ---- */
    water: [
      "Water nearby. You may fly it, never land in it.",
      "The pond is close enough to matter. Count carefully.",
      "You can carry water. You cannot swim.",
      "Water doesn't block the shot, only the landing.",
      "Check the landing dot before you commit. That's the whole trick.",
      "Flying over is legal. Stopping short is not.",
      "The water is patient and it is very close.",
      "One dot wrong and you're wet. Count twice.",
      "You may soar over it. Landing is the problem.",
      "Water is a landing hazard, not a flight hazard.",
      "Nothing wrong with going over. Everything wrong with going in.",
      "The pond has caught better players. Allegedly.",
      "Measure the landing square, not the pretty line.",
      "Carry it or avoid it. There's no third option.",
      "Water's only rule: don't stop there.",
      "The hazard is close. Precision just got expensive.",
      "You can fly the pond. Make sure the number lands you past it.",
      "Wet is the one outcome with no recovery shot.",
      "The lake doesn't care how good the line looked.",
      "Plan the landing dot. The rest is scenery.",
      "The pond is one bad count away.",
      "Fly it or ignore it. Landing is not on the menu.",
      "Water punishes the landing square only. Check yours.",
      "The hazard is adjacent. Adjacency has consequences.",
      "Over is fine. In is not.",
      "You can pass above the water freely. Just don't stop.",
      "The lake is close enough to be a factor. Count it in.",
      "One dot short and you're swimming.",
      "It's a landing problem, not a flying problem.",
      "The pond doesn't block your line. It blocks your finish."
    ],

    /* ---- a long way from the cup ---- */
    trouble: [
      "Awkward spot. Take your medicine and move on.",
      "Getting out is a fine ambition right now.",
      "The bold line is a trap. The boring line is a score.",
      "Somewhere, a mulligan is quietly clearing its throat.",
      "Long way home. Start walking.",
      "This is a two-shot problem. Treat it like one.",
      "Distance is the enemy now. Chip away.",
      "You're a long way out. Panic is not a strategy.",
      "The cup is a rumour from here.",
      "Big picture: just get closer. That's the whole plan.",
      "Nothing heroic. Heroic costs three strokes.",
      "This hole has gotten away from you. Reel it back slowly.",
      "The scenic route. Enjoy the trees.",
      "You need distance, not drama.",
      "Progress is the only goal from this far out.",
      "A long way from the cup, a long way from panic. Stay there.",
      "Two good shots beat one miraculous one.",
      "The map is large and you are far from the interesting part.",
      "Take the yardage. Worry about accuracy later.",
      "This is a rebuilding shot. Build.",
      "You've found the quiet part of the course.",
      "Nothing to do but advance the ball and keep your dignity.",
      "You're a long way out. Shorten it, don't solve it.",
      "This is a shot about getting closer, nothing more.",
      "Distance first. Everything else later.",
      "The cup is theoretical from here.",
      "Advance the ball. That's the whole ambition.",
      "You're deep in the map's quiet corner.",
      "Two sensible shots will fix this. One wild one won't.",
      "Nothing to do but make the number smaller."
    ],

    /* ---- seven or more strokes on the hole ---- */
    deep: [
      "This hole has become a character-building exercise.",
      "Par is a memory. Let's aim for dignity.",
      "Six strokes in and still writing. That's commitment.",
      "The pencil is getting shorter. So is the patience.",
      "At this point, finishing is the achievement.",
      "The scorecard has stopped taking notes.",
      "Every round has one of these holes. This is yours.",
      "We're well past par. We're into folklore now.",
      "Keep going. The next hole is a fresh sheet.",
      "This is no longer about the score. It's about closure.",
      "The mercy pickup is at 12, just so you know it exists.",
      "Somewhere, par is having a lovely afternoon without you.",
      "You've seen more of this hole than the designer did.",
      "Persistence is a virtue. Usually.",
      "The die has made its feelings clear.",
      "Let's just get it in the cup and never speak of it.",
      "Statistically, something good has to happen eventually.",
      "This hole owes you nothing and has paid nothing.",
      "You're deep in the notebook now.",
      "The good news: it can only last so long.",
      "Grind it out. Grinding counts.",
      "Every stroke from here is a story you'll tell badly.",
      "The cup is still there. Somewhere. Allegedly.",
      "Finish the hole. Forgive yourself later.",
      "The hole has stopped being a competition and started being an experience.",
      "You're writing a long entry in a short box.",
      "Par has left. Bogey is packing.",
      "This hole is now purely about finishing.",
      "The die owes you an apology it will never give.",
      "Keep swinging. It ends eventually.",
      "There's a mercy pickup at twelve. Consider it a horizon.",
      "Every round needs a disaster hole for contrast."
    ],

    /* ---- teeing off on the eighteenth ---- */
    final: [
      "Last hole. Whatever the card says, it says it soon.",
      "Eighteen. One more sheet and the notebook closes.",
      "The final tee. Finish the way you'd like to remember it.",
      "Last hole. No point saving anything now.",
      "One hole left. Spend every mulligan you've got.",
      "The closing hole. Make it a good story.",
      "Eighteen holes, one last decision tree.",
      "Final hole. The pencil is nearly done.",
      "Last chance to fix the arithmetic.",
      "This is the one you'll describe afterwards. Choose your line.",
      "The end is in sight. Don't rush the last part.",
      "One more hole, then the scorecard tells the truth.",
      "Eighteenth tee. Everything counts and nothing is left.",
      "Last sheet of paper. Make it interesting.",
      "The closing hole. No reason to hold anything back.",
      "One more, then the arithmetic is final."
    ],

    /* ---- multiplayer: comfortably ahead ---- */
    lead: [
      "You're ahead. Ahead is a fragile condition.",
      "Leading the card. Play the boring shot.",
      "You're in front. Protect it without freezing.",
      "A lead is a loan from the die. It gets called in.",
      "Ahead on strokes. Don't donate them back.",
      "You're winning. Nobody has ever lost by playing sensibly.",
      "The lead is yours. The pressure comes free.",
      "Ahead by a bit. Boring golf is now your best golf.",
      "You're up. Take the safe line and look smug later.",
      "Leading. This is when clever ideas become expensive.",
      "In front for now. The die has no loyalty.",
      "You're ahead. Act like you're not.",
      "You're in front. Front-runners lose by getting fancy.",
      "Ahead on the card. Keep the shots boring and the lead intact.",
      "Leading. The safest line is now the smartest one.",
      "You're up. Nothing clever required."
    ],

    /* ---- multiplayer: comfortably behind ---- */
    behind: [
      "You're behind. Time to take a line you'd normally refuse.",
      "Down on strokes. Aggression is now the sensible choice.",
      "Behind the pace. Something has to change, and it's you.",
      "You're chasing. Chasing is more fun anyway.",
      "Down a few. Fortune favours the impatient here.",
      "Trailing. The safe shot won't close the gap.",
      "You're behind, which means the interesting line is the correct line.",
      "Nothing to protect. That's a kind of freedom.",
      "Down on the card. Go get it back.",
      "Behind means the risky shot is finally justified.",
      "You're chasing the card. Take the aggressive number.",
      "Trailing. Play like you've got nothing to lose, because you don't.",
      "Behind on the card. Now is when risk pays.",
      "You're chasing, which makes the bold line correct.",
      "Down a few strokes. Take the shot you've been avoiding.",
      "Trailing. Safe golf won't fix this."
    ],

    /* ---- overflow: fits any situation ---- */
    general: [
      "The die is fair. It is not kind.",
      "Golf is a simple game played by complicated people.",
      "Somewhere on this course is a good shot with your name on it.",
      "The notebook keeps score. It does not keep grudges.",
      "Every hole is negotiable until it isn't.",
      "Pick a direction and commit. Hesitation isn't a shot.",
      "The dots don't move. Everything else does.",
      "Golf: the slow accumulation of small decisions.",
      "There's no wind here. Blame something else.",
      "A par is just a bogey that behaved.",
      "The cup has infinite patience. You do not.",
      "Play the shot in front of you, not the one you wanted.",
      "The best line is usually the second one you thought of.",
      "Nobody remembers the middle of a round. Make this the exception.",
      "Trust the arithmetic over the instinct.",
      "The die owes you nothing. It never has.",
      "Small good decisions. That's the whole game.",
      "This is a game of dots and regrets.",
      "Every shot is a fresh problem. Solve this one.",
      "The scorecard is a very patient historian.",
      "Golf rewards patience and punishes everything else.",
      "There's a right answer here. There's usually two.",
      "Count the squares. Then count them again.",
      "The map is honest. The die is indifferent.",
      "Somewhere a par is still possible. Probably.",
      "One shot at a time. The cliche survives because it works.",
      "Direction first, distance second, hope third.",
      "The course was built fairly. That's all anyone promised.",
      "You can't control the number. You can control the line.",
      "Every notebook round has a turning point. Could be now.",
      "Aim for the outcome you can live with.",
      "Good golf is mostly avoiding the stupid option.",
      "The die decides how far. You decide where.",
      "A quiet shot is worth two spectacular ones.",
      "Play the percentages. Then complain about them.",
      "This is a puzzle, not a fight.",
      "The pencil is cheap. The strokes are not.",
      "Look at the whole board before you commit.",
      "There's always a safe line. It's rarely satisfying.",
      "Golf is a long argument with arithmetic.",
      "A bad shot and a good shot cost the same amount of pencil.",
      "The course doesn't know you're trying.",
      "Half of golf is deciding. The other half is regretting.",
      "The die has no memory of the last roll. Neither should you.",
      "Every shot is a small argument with geometry.",
      "The cup isn't going anywhere. Take the moment.",
      "Good decisions are quieter than good luck.",
      "The map rewards reading it properly.",
      "There's usually a safe answer and an interesting one.",
      "Golf is arithmetic wearing a hat.",
      "The best players just make fewer expensive mistakes.",
      "Look before you commit. It's free.",
      "The die is honest. That's the problem.",
      "Nothing on this course is personal.",
      "A stroke saved is worth two struck well.",
      "Patience is the only club that never fails.",
      "Somewhere in this round is a shot you'll be proud of.",
      "The pencil records everything and forgives nothing.",
      "Play the board, not the mood.",
      "You can't out-roll the die. You can out-think the map.",
      "Every hole is a small negotiation with chance.",
      "There is no perfect shot, only sensible ones.",
      "Count carefully. Regret is expensive.",
      "The line matters more than the number.",
      "Steady beats spectacular over eighteen holes.",
      "The course was fair before you got here.",
      "This shot only needs to be good enough.",
      "Nobody wins a round in one swing. Plenty lose one that way.",
      "Read the terrain. It's telling you something.",
      "A quiet hole is a good hole.",
      "The die decides the distance, not the outcome.",
      "Ambition is fine. Unplanned ambition isn't.",
      "The scorecard has seen worse. Probably.",
      "Take the shot the position offers you.",
      "Small margins, long round.",
      "Every good round contains at least one act of restraint.",
      "The map is fixed. Your approach isn't.",
      "There's no luck in choosing a direction.",
      "Trust the count over the feeling.",
      "Good golf looks boring from the outside.",
      "The hole doesn't care how you get there.",
      "One sensible shot, then another. That's the method.",
      "The die will even out. Your decisions won't.",
      "This is a game of small corrections.",
      "Nothing here rewards hurry.",
      "Distance is luck. Direction is skill.",
      "The notebook is patient with everyone equally.",
      "A well-chosen line survives a bad roll.",
      "Consider the boring option seriously.",
      "The course offers a solution. Find it.",
      "Chance handles the number. You handle the rest.",
      "Every stroke is a decision you get to keep.",
      "Play for position, not for applause.",
      "The cup rewards planning more than power.",
      "There's always another shot. Until there isn't.",
      "Golf is mostly waiting for arithmetic to agree with you.",
      "The right answer is usually the unexciting one.",
      "A clean decision beats a lucky one.",
      "Don't fight the map. Use it.",
      "The die is indifferent. Be more interesting than it.",
      "Somewhere a par is waiting to be assembled.",
      "Take stock before you take the shot.",
      "The scorecard doesn't record intentions.",
      "You've got dots to spare. Spend them deliberately.",
      "Aim where a bad roll still leaves you fine.",
      "Every shot has a safe version. Consider it first.",
      "The best line survives the worst number.",
      "Hesitation costs nothing. Rushing costs strokes.",
      "The map is generous if you read it.",
      "This is a thinking game with a rolling component.",
      "A good position is worth more than a good roll.",
      "Chance is loud. Strategy is quiet.",
      "Play the shot that leaves you a shot.",
      "The course is indifferent. Take advantage.",
      "Nothing improves by being rushed.",
      "There's a version of this shot you won't regret.",
      "Plan two shots ahead. Play only one.",
      "The pencil is the only thing keeping score.",
      "Every hole ends. Some just take longer.",
      "The cup is patient. Match it."
    ]
  };

  let queues = {};
  let used = new Set();

  function shuffle(arr, rng) {
    const a = arr.slice();
    for (let i = a.length - 1; i > 0; i--) {
      const j = (rng() * (i + 1)) | 0;
      const t = a[i]; a[i] = a[j]; a[j] = t;
    }
    return a;
  }

  function build(seed) {
    queues = {};
    for (const k in LINES) queues[k] = shuffle(LINES[k], global.RNG.rngFor(seed + "|caddie|" + k));
  }

  /** Start a fresh round. Same seed = same order, but never a repeat. */
  function init(seed) {
    build(seed || "0");
    used = new Set();
  }

  function drawFrom(key) {
    const q = queues[key];
    if (!q) return null;
    while (q.length) {
      const line = q.shift();
      if (!used.has(line)) { used.add(line); return line; }
    }
    return null;
  }

  /**
   * Take the next unseen line for a situation. Falls back to the neutral pool,
   * and only if literally every line has been shown does it start over.
   */
  function take(bucket) {
    let line = drawFrom(bucket);
    if (line) return line;
    line = drawFrom("general");
    if (line) return line;
    init(String(Math.random()));            // everything exhausted: fresh deck
    return drawFrom(bucket) || drawFrom("general") || "Play well.";
  }

  function stats() {
    const per = {};
    let total = 0;
    for (const k in LINES) { per[k] = LINES[k].length; total += per[k]; }
    return { per, total, used: used.size };
  }

  global.Caddie = { init, take, stats, LINES };
})(typeof window !== "undefined" ? window : globalThis);
